spring.config.import=aws-parameterstore:/camp-health-app/prod/
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.s3.bucket=ch4cloud-bucket

management.endpoint.health.show-details=never
management.info.env.enabled=true

info.app.message=${APP_MESSAGE}
info.team-name=${team-name}

logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false