spring.profiles.active=prod
# spring.cloud.aws.parameterstore.enabled=false

logging.level.root=INFO
logging.level.com.example.ch4cloud=INFO

# 파일 업로드 크기 제한
spring.servlet.multipart.max-file-size=10MB

management.endpoints.web.exposure.include=health, info